name: Frontend / Unit Tests

on:
  pull_request:
    branches: [main, develop]

permissions:
  pull-requests: write
  contents: read

jobs:
  unit-test:
    uses: juv-dev/workflows-frontend/.github/workflows/pr-unit-test.yml@v1.1.0
    secrets: inherit
